"""
Generates FIO .ini job files and standalone shell scripts from a Workflow.
"""
from __future__ import annotations

import os
import stat
import textwrap
from pathlib import Path
from typing import Union

from .workflow import FIOJobConfig, GlobalFIOConfig, Workflow, WorkflowStep


def _merge_fio_config(global_cfg: GlobalFIOConfig, job_cfg: FIOJobConfig) -> dict:
    """Merge step-level FIO config on top of global defaults."""
    merged = global_cfg.to_dict()
    merged.update({k: v for k, v in job_cfg.to_dict().items() if v is not None})
    return merged


def generate_fio_job_file(
    step: WorkflowStep,
    global_cfg: GlobalFIOConfig,
    output_path: Union[str, Path],
) -> Path:
    """Write an .ini FIO job file for the given step and return its path."""
    if step.type != "fio" or step.fio is None:
        raise ValueError(f"Step '{step.name}' is not a FIO step")

    cfg = _merge_fio_config(global_cfg, step.fio)
    lines = ["[global]"]
    # Global section – everything except rw/bs/iodepth which are job-level
    job_only_keys = {"rw", "bs", "iodepth", "numjobs", "rwmixread"}
    for k, v in cfg.items():
        if k not in job_only_keys:
            lines.append(f"{k}={v}")

    lines.append("")
    lines.append(f"[{step.name}]")
    for k in ("rw", "bs", "iodepth", "numjobs", "rwmixread"):
        if k in cfg and cfg[k] is not None:
            lines.append(f"{k}={cfg[k]}")
    # Any extra options from step.fio.extra
    for k, v in step.fio.extra.items():
        lines.append(f"{k}={v}")

    output_path = Path(output_path)
    output_path.write_text("\n".join(lines) + "\n")
    return output_path


def generate_standalone_script(workflow: Workflow, output_dir: Union[str, Path]) -> Path:
    """
    Generate a self-contained bash script + all FIO job files so the
    workflow can be executed without the GUI or Python runtime.

    Layout:
        output_dir/
        ├── run_workflow.sh        ← execute this
        ├── fio_jobs/
        │   ├── 001_<name>.ini
        │   └── ...
        └── workflow.yaml          ← copy of the workflow definition
    """
    output_dir = Path(output_dir)
    jobs_dir = output_dir / "fio_jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    # Write workflow YAML copy
    (output_dir / "workflow.yaml").write_text(workflow.to_yaml())

    script_lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by fio_bench – DO NOT EDIT BY HAND",
        f"# Workflow: {workflow.name}",
        f"# Description: {workflow.description}",
        "",
        "set -euo pipefail",
        "",
        "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
        f"RESULTS_DIR=\"{workflow.output_dir}/$(date +%Y%m%d_%H%M%S)\"",
        "mkdir -p \"$RESULTS_DIR\"",
        "",
        "log() { echo \"[$(date +%H:%M:%S)] $*\" | tee -a \"$RESULTS_DIR/run.log\"; }",
        "run_step_meta() {",
        "    local step_dir=$1 exit_code=$2 start_ts=$3",
        "    local end_ts; end_ts=$(date +%s%N)",
        "    local dur=$(( (end_ts - start_ts) / 1000000 ))",
        "    cat > \"$step_dir/meta.json\" <<EOF",
        '{',
        '  "exit_code": '"$exit_code"',',
        '  "duration_ms": '"$dur"',',
        '  "timestamp": "'"$(date -Iseconds)"'"',
        '}',
        "EOF",
        "}",
        "",
        f'log "Starting workflow: {workflow.name}"',
        f'log "Results → $RESULTS_DIR"',
        "",
    ]

    enabled = workflow.enabled_steps()
    for idx, step in enumerate(enabled, start=1):
        prefix = f"{idx:03d}_{step.name}"
        step_dir_var = f"STEP_{idx:03d}_DIR"

        script_lines += [
            f"# {'─' * 60}",
            f"# Step {idx:03d}: [{step.type.upper()}] {step.name}",
            f"# {'─' * 60}",
            f'{step_dir_var}="$RESULTS_DIR/{prefix}"',
            f'mkdir -p "${step_dir_var}"',
            f'log "Step {idx}/{len(enabled)}: {step.name}"',
            f'_STEP_START=$(date +%s%N)',
        ]

        if step.type == "fio":
            job_file = jobs_dir / f"{prefix}.ini"
            generate_fio_job_file(step, workflow.global_fio, job_file)
            rel_job = f"$SCRIPT_DIR/fio_jobs/{prefix}.ini"
            script_lines += [
                f'cp "{rel_job}" "${step_dir_var}/fio_job.ini"',
                f'fio --output-format=json \\',
                f'    --output="${step_dir_var}/fio_out.json" \\',
                f'    "{rel_job}" \\',
                f'    2>&1 | tee "${step_dir_var}/fio_out.txt"',
                f'_STEP_EXIT=$?',
            ]
        elif step.type == "command":
            cmd_parts = []
            for cmd_entry in step.commands:
                prefix_cmd = "sudo " if cmd_entry.sudo else ""
                escaped = cmd_entry.cmd.replace('"', '\\"')
                timeout_val = cmd_entry.timeout
                ignore = "|| true" if cmd_entry.ignore_errors else ""
                cmd_parts += [
                    f'log "  cmd: {cmd_entry.label}"',
                    f'timeout {timeout_val} {prefix_cmd}{escaped} \\',
                    f'    > "${step_dir_var}/{cmd_entry.label}.txt" 2>&1 {ignore}',
                ]
            script_lines += cmd_parts
            script_lines.append("_STEP_EXIT=0")

        script_lines += [
            f'run_step_meta "${step_dir_var}" "$_STEP_EXIT" "$_STEP_START"',
            f'log "  done (exit=$_STEP_EXIT)"',
            "",
        ]

    script_lines += [
        'log "Workflow complete. Results in $RESULTS_DIR"',
        'echo "$RESULTS_DIR"',
    ]

    script_path = output_dir / "run_workflow.sh"
    script_path.write_text("\n".join(script_lines) + "\n")
    script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return script_path
